name: taskcluster push worker
on: [push]
jobs:
  osx-tc-worker-push:
    runs-on: macos-latest
    env:
      TASKCLUSTER_ACCESS_TOKEN: ${{ secrets.TASKCLUSTER_ACCESS_TOKEN }}
      TC_WORKER_ID: "gh-grizzly-push-${{ github.run_id }}-${{ github.run_attempt }}"
    steps:
      - uses: actions/checkout@v2
      - run: .github/scripts/start-worker.sh
