name: taskcluster PR worker
on: [pull_request]
jobs:
  osx-tc-worker-pr:
    runs-on: macos-latest
    env:
      TASKCLUSTER_ACCESS_TOKEN: ${{ secrets.TASKCLUSTER_ACCESS_TOKEN }}
      TC_WORKER_ID: "gh-grizzly-pr-${{ github.run_id }}-${{ github.run_attempt }}"
    steps:
      - uses: actions/checkout@v2
      - run: .github/scripts/start-worker.sh
